CREATE TABLE carts (cart_id bigint generated BY DEFAULT AS IDENTITY, all_price DECIMAL(19,2), PRIMARY KEY (cart_id))
CREATE TABLE carts_product_list (cart_cart_id bigint NOT NULL, product_list_product_id bigint NOT NULL)
CREATE TABLE persons (person_id bigint generated BY DEFAULT AS IDENTITY, age integer, first_name varchar(30) NOT NULL, last_name varchar(50) NOT NULL, phone varchar(20) NOT NULL, shop_id bigint, PRIMARY KEY (person_id))
CREATE TABLE persons_carts (person_person_id bigint NOT NULL, carts_cart_id bigint NOT NULL)
CREATE TABLE products (product_id bigint generated BY DEFAULT AS IDENTITY, name varchar(255) NOT NULL, price decimal(19,2) NOT NULL, products bigint, PRIMARY KEY (product_id))
CREATE TABLE shops (shop_id bigint generated BY DEFAULT AS IDENTITY, name varchar(255) NOT NULL, PRIMARY KEY (shop_id))
ALTER TABLE persons_carts DROP CONSTRAINT if EXISTS UK_ekwp7jet6rbbyh8w9wiksylrd
ALTER TABLE persons_carts ADD CONSTRAINT UK_ekwp7jet6rbbyh8w9wiksylrd UNIQUE (carts_cart_id)
ALTER TABLE carts_product_list ADD CONSTRAINT FKkugj1u7vkv167ig4s0d700s4u FOREIGN KEY (product_list_product_id) REFERENCES products
ALTER TABLE carts_product_list ADD CONSTRAINT FK7fc0of5pwygxhopnrh3wvm4w4 FOREIGN KEY (cart_cart_id) REFERENCES carts
ALTER TABLE persons ADD CONSTRAINT FKr6xk8urcu6ay3qgogabdb9xrb FOREIGN KEY (shop_id) references shops
ALTER TABLE persons_carts ADD CONSTRAINT FKotcg93yhoeqnpddu42n4un7vd FOREIGN KEY (carts_cart_id) REFERENCES carts
ALTER TABLE persons_carts ADD CONSTRAINT FKj9q71v9vq94gq0r8oy31yupbv FOREIGN KEY (person_person_id) REFERENCES persons
ALTER TABLE products ADD CONSTRAINT FKrpnmgq1didh2fqurcq492v9tu FOREIGN KEY (products) REFERENCES shops